Comma() is 2.5 faster now
dustin/go-humanize pull request #102
Opened 2022-03-20 11:41 UTC by kaatinga

Hi there!

Decided to leetcode `Comma()`. The result is in this PR. Managed to get rid of allocations, removed 2 dependencies and reduced the execution time.

```
goos: darwin
goarch: arm64
pkg: github.com/kaatinga/krendel
BenchmarkComma
BenchmarkComma-8          	 5709186	       207.5 ns/op	      50 B/op	       8 allocs/op
BenchmarkInt64_String
BenchmarkInt64_String-8   	13717701	        86.55 ns/op	      64 B/op	       4 allocs/op
PASS
```

2024-03-20 14:31 UTC, dolmen requested changes

2024-03-25 15:43 UTC, dolmen commented
I think that #120 should be merged first. Not because I wrote it, but because it adds automated tests that will give more confidence in the impact of the changes here.

2024-03-25 16:05 UTC, kaatinga commented
sure @dolmen , it waited 2 years and can wait a bit longer. Hope your PR will be merged soon :)

2025-05-12 05:49 UTC, dustin commented
I'm incredibly bad at being aware of what stuff is open on GitHub.  Apologies.

2025-05-12 05:50 UTC, merged

2025-05-12 06:41 UTC, kaatinga commented
@dustin thanks for keeping this repo maintained!

2025-05-13 21:59 UTC, dustin commented
I do kind of wish I were doing it better.  I've got a couple hundred repos and github makes it kind of hard for me to know where activity is.  :/